<x-frontend.layout :site-settings="$siteSettings" title="Contact" active="contact">
    <section class="bg-ink text-white pt-16 pb-20 md:pt-24 md:pb-24 relative overflow-hidden">
        <div class="grid-drift opacity-[.14]"></div>
        <div class="shell relative"><span class="eyebrow on-dark">Contact</span><h1 class="mt-6 text-white text-[clamp(34px,5.6vw,56px)] max-w-3xl">Come in, call the right desk, or send it in writing</h1><p class="mt-6 text-white/75 text-[17px] leading-relaxed max-w-2xl">Pick the number or channel that matches your question.</p></div>
    </section>
    <section class="section bg-white"><div class="shell"><span class="eyebrow">Direct lines</span><h2 class="h-sec mt-5 max-w-lg">Who to call about what</h2><div class="mt-11 grid gap-5 md:grid-cols-3">
        <div class="card p-7" data-reveal><h3 class="text-[19px]">PR & Admission</h3><p class="mt-2.5 text-[14.5px] text-muted leading-relaxed">New enrolments, course advice, fees and placement assessment booking.</p>@if($siteSettings?->contact_phone)<div class="mt-5"><a href="tel:{{ $siteSettings->contact_phone }}" class="text-flame-deep font-semibold text-[16px]">{{ $siteSettings->contact_phone }}</a></div>@endif</div>
        <div class="card p-7" data-reveal><h3 class="text-[19px]">Email</h3><p class="mt-2.5 text-[14.5px] text-muted leading-relaxed">Send your documents, questions, result or admission request.</p>@if($siteSettings?->contact_email)<div class="mt-5"><a href="mailto:{{ $siteSettings->contact_email }}" class="text-flame-deep font-semibold text-[16px]">{{ $siteSettings->contact_email }}</a></div>@endif</div>
        <div class="card p-7" data-reveal><h3 class="text-[19px]">Campus</h3><p class="mt-2.5 text-[14.5px] text-muted leading-relaxed">{{ $siteSettings?->address ?: 'Narsingdi Sadar, Bangladesh' }}</p></div>
    </div></div></section>
    <section class="section bg-mist"><div class="shell grid gap-12 lg:grid-cols-[1.15fr_1fr] lg:gap-16 items-start"><div class="rounded-2xl bg-white border border-line p-7 md:p-9"><span class="eyebrow">Send a message</span><h2 class="text-[27px] mt-5">Tell us what you need and we will call you back</h2><form class="mt-8 grid gap-5"><div class="grid gap-5 sm:grid-cols-2"><input class="field" placeholder="Full name"><input class="field" placeholder="Mobile number"></div><input class="field" placeholder="Email"><textarea class="field" rows="5" placeholder="Your message"></textarea><button type="button" class="btn btn-primary">Send message</button></form></div><div class="rounded-2xl border border-line overflow-hidden bg-white"><iframe title="STS Institute location" src="https://www.google.com/maps?q=Narsingdi%20Sadar%2C%20Narsingdi%2C%20Bangladesh&output=embed" class="w-full h-[360px] block border-0" loading="lazy"></iframe></div></div></section>
</x-frontend.layout>
