@php
    $eventCards = $landingPage?->event_section ?: [
        ['date' => '15', 'month' => 'Sep', 'title' => 'Collector Preview', 'location' => 'Online Viewing Room', 'time' => '7:00 PM'],
        ['date' => '28', 'month' => 'Sep', 'title' => 'Emerging Artist Showcase', 'location' => 'ART Story Catalogue', 'time' => '6:30 PM'],
        ['date' => '12', 'month' => 'Oct', 'title' => 'Studio Stories Session', 'location' => 'Virtual Event', 'time' => '8:00 PM'],
    ];
    $exhibitionSection = $landingPage?->exhibition_section ?: \App\Models\LandingPage::defaults()['exhibition_section'];
@endphp
<x-artstory.layout :site-settings="$siteSettings" title="Events & PR" active="events">
    <main>
        <section class="relative overflow-hidden bg-[#111318] text-white"><div class="absolute inset-y-0 right-0 hidden w-1/2 bg-[radial-gradient(circle_at_center,_rgba(167,161,83,.24),_transparent_62%)] lg:block"></div><div class="relative mx-auto grid max-w-7xl grid-cols-1 gap-10 px-6 py-20 md:py-28 lg:grid-cols-[1fr_0.8fr] lg:items-end"><div><p class="text-xs font-black uppercase tracking-[0.3em] text-[#c6bd78]">Events & PR</p><h1 class="mt-6 max-w-3xl font-display text-5xl font-semibold leading-[1.05] md:text-7xl">Meet the stories behind the work.</h1></div><p class="max-w-xl text-lg leading-8 text-white/70">{{ $exhibitionSection['description'] ?? 'Join ART Story previews, artist-focused sessions, and collection moments created for collectors, artists, and art lovers.' }}</p></div></section>
        @if ($events->isNotEmpty())
            <section class="bg-[#f5f4f1] py-20 md:py-24"><div class="mx-auto max-w-7xl px-6"><div class="flex flex-col gap-4 border-b border-gray-300 pb-7 md:flex-row md:items-end md:justify-between"><div><p class="text-xs font-black uppercase tracking-[0.24em] text-[#88884d]">The programme</p><h2 class="mt-3 font-display text-4xl font-semibold text-black md:text-5xl">What’s happening</h2></div><p class="max-w-md text-sm leading-7 text-gray-600">Discover upcoming gatherings, viewing rooms, announcements, and stories from the ART Story community.</p></div><div class="mt-10 grid grid-cols-1 gap-6 lg:grid-cols-2">@foreach ($events as $event)<a href="{{ route('events.show', $event) }}" class="group grid grid-cols-[88px_1fr] gap-6 border border-gray-200 bg-white p-5 transition duration-300 hover:-translate-y-1 hover:border-black hover:shadow-xl hover:shadow-black/10 sm:grid-cols-[118px_1fr] sm:p-7"><div class="flex aspect-square flex-col items-center justify-center border border-gray-300 bg-[#fafaf8] text-center"><span class="font-display text-4xl font-semibold text-black sm:text-5xl">{{ $event->start_date?->format('d') ?: '—' }}</span><span class="mt-1 text-[11px] font-black uppercase tracking-[0.18em] text-[#88884d]">{{ $event->start_date?->format('M Y') ?: 'Update' }}</span></div><div class="flex min-w-0 flex-col justify-center"><p class="text-[11px] font-black uppercase tracking-[0.2em] text-[#88884d]">{{ $event->content_type === 'pr' ? 'PR / News' : 'Event' }}@if($event->location) <span class="text-gray-400">/</span> {{ $event->location }}@endif</p><h3 class="mt-3 font-display text-2xl font-semibold leading-tight text-black sm:text-3xl">{{ $event->name }}</h3><p class="mt-3 line-clamp-2 text-sm leading-6 text-gray-600">{{ $event->excerpt ?: 'Explore the latest ART Story programme.' }}</p><span class="mt-5 text-xs font-black uppercase tracking-[0.15em] text-black transition group-hover:text-[#88884d]">Explore story <span class="ml-2 text-base">→</span></span></div></a>@endforeach</div></div></section>
        @else
            <section class="bg-[#f5f4f1] py-20 md:py-24"><div class="mx-auto max-w-7xl px-6"><div class="border-b border-gray-300 pb-7"><p class="text-xs font-black uppercase tracking-[0.24em] text-[#88884d]">The programme</p><h2 class="mt-3 font-display text-4xl font-semibold text-black md:text-5xl">Upcoming moments</h2></div><div class="mt-10 space-y-5">@foreach ($eventCards as $event)<article class="grid grid-cols-1 gap-6 border border-gray-200 bg-white p-6 md:grid-cols-[118px_1fr_auto] md:items-center"><div class="flex aspect-square max-w-[118px] flex-col items-center justify-center border border-gray-300 bg-[#fafaf8] text-center"><span class="font-display text-4xl font-semibold">{{ $event['date'] }}</span><span class="text-xs font-black uppercase tracking-[0.2em] text-[#88884d]">{{ $event['month'] }}</span></div><div><p class="text-xs font-black uppercase tracking-[0.18em] text-[#88884d]">{{ $event['time'] }} / {{ $event['location'] }}</p><h2 class="mt-2 font-display text-3xl font-semibold text-black">{{ $event['title'] }}</h2></div><a href="{{ route('contact') }}" class="text-xs font-black uppercase tracking-[0.14em] underline underline-offset-8">Inquire →</a></article>@endforeach</div></div></section>
        @endif
        <section class="bg-white py-20 md:py-24"><div class="mx-auto max-w-7xl px-6"><div class="flex flex-col gap-4 border-b border-gray-200 pb-7 md:flex-row md:items-end md:justify-between"><div><p class="text-xs font-black uppercase tracking-[0.24em] text-gray-500">From the catalogue</p><h2 class="mt-3 font-display text-4xl font-semibold text-black md:text-5xl">Works in conversation</h2></div><a href="{{ route('artworks.index') }}" class="text-xs font-black uppercase tracking-[0.15em] text-black underline underline-offset-8">View all artworks →</a></div><div class="mt-10 grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-4">@forelse ($featuredArtworks as $artwork)@include('artstory.partials.artwork-card', ['artwork' => $artwork])@empty<div class="col-span-full border border-dashed border-gray-300 p-12 text-center text-gray-500">Add active artworks to show event previews here.</div>@endforelse</div></div></section>
    </main>
</x-artstory.layout>
